### PR TITLE
Add ReversingLabs playbooks

### PR DESCRIPTION
**Pull request by ivukovicRL**

### CODE REVIEW

**Comment by MislavReversingLabs** [comment]
@ljstella @kelby-shelton Hi, are you the ones responsible for reviewing and closing playbook pull requests here or should we do it for ourselves?

**Review by rosplk — APPROVED** [review]

**Comment by MislavReversingLabs** [comment]
Requesting this PR to be closed so we can open up a new one into the 6.1 branch.

**Comment by kelby-shelton** [comment]
Closing per Slack request by Mislav Sever in favor of a new PR.

**Comment by MislavReversingLabs** [comment]
New pull request: https://github.com/phantomcyber/playbooks/pull/163

**Pull request closed without merging**
