### PR TITLE
ReversingLabs reported email triage

### PR DESCRIPTION
**Pull request by MislavReversingLabs**

### CODE REVIEW

**Comment by MislavReversingLabs** [comment]
@kelby-shelton When can we start working on this PR?

**Comment by kelby-shelton** [comment]
> @kelby-shelton When can we start working on this PR?

I looked at the submission and it appears that the automated checks are not running so I ran them manually. These are the problems that were found:


20241029 13:48:43.896 | ERROR | Block 'run_query_1' is not named |  
-- | -- | -- | --
20241029 13:48:43.898 | ERROR | Block 'get_email_1' is not named |  
20241029 13:48:43.900 | ERROR | Block 'detonate_file_1' is not named |  
20241029 13:48:43.901 | ERROR | Block 'get_summary_report_1' is not named |  
20241029 13:48:43.903 | ERROR | Block 'filter_2' is not named |  
20241029 13:48:43.907 | ERROR | Block 'run_query_1' does not have notes |  
20241029 13:48:43.908 | ERROR | Block 'get_email_1' does not have notes |  
20241029 13:48:43.909 | ERROR | Block 'detonate_file_1' does not have notes |  
20241029 13:48:43.910 | ERROR | Block 'get_summary_report_1' does not have notes |  
20241029 13:48:43.911 | ERROR | Block 'filter_2' does not have notes |  
20241029 13:48:43.929 | ERROR | Incorrect asset name in block 'run_query_1' |  
20241029 13:48:43.931 | ERROR | Incorrect asset name in block 'get_email_1' |  
20241029 13:48:43.932 | ERROR | Incorrect asset name in block 'detonate_file_1' |  
20241029 13:48:43.934 | ERROR | Incorrect asset name in block 'get_summary_report_1'

[20241029 13:48:43.896](https://github.com/phantomcyber/playbooks/pull/196#s1-t8-k1-k4-k3-k2-k1)	ERROR	Block 'run_query_1' is not named	
[20241029 13:48:43.898](https://github.com/phantomcyber/playbooks/pull/196#s1-t8-k1-k4-k4-k2-k1)	ERROR	Block 'get_email_1' is not named	
[20241029 13:48:43.900](https://github.com/phantomcyber/playbooks/pull/196#s1-t8-k1-k4-k5-k2-k1)	ERROR	Block 'detonate_file_1' is not named	
[20241029 13:48:43.901](https://github.com/phantomcyber/playbooks/pull/196#s1-t8-k1-k4-k6-k2-k1)	ERROR	Block 'get_summary_report_1' is not named	
[20241029 13:48:43.903](https://github.com/phantomcyber/playbooks/pull/196#s1-t8-k1-k4-k7-k2-k1)	ERROR	Block 'filter_2' is not named	
[20241029 13:48:43.907](https://github.com/phantomcyber/playbooks/pull/196#s1-t9-k1-k4-k3-k1-k1-k1)	ERROR	Block 'run_query_1' does not have notes	
[20241029 13:48:43.908](https://github.com/phantomcyber/playbooks/pull/196#s1-t9-k1-k4-k4-k1-k1-k1)	ERROR	Block 'get_email_1' does not have notes	
[20241029 13:48:43.909](https://github.com/phantomcyber/playbooks/pull/196#s1-t9-k1-k4-k5-k1-k1-k1)	ERROR	Block 'detonate_file_1' does not have notes	
[20241029 13:48:43.910](https://github.com/phantomcyber/playbooks/pull/196#s1-t9-k1-k4-k6-k1-k1-k1)	ERROR	Block 'get_summary_report_1' does not have notes	
[20241029 13:48:43.911](https://github.com/phantomcyber/playbooks/pull/196#s1-t9-k1-k4-k7-k1-k1-k1)	ERROR	Block 'filter_2' does not have notes	
[20241029 13:48:43.929](https://github.com/phantomcyber/playbooks/pull/196#s1-t13-k1-k3-k1-k4-k1)	ERROR	Incorrect asset name in block 'run_query_1'	
[20241029 13:48:43.931](https://github.com/phantomcyber/playbooks/pull/196#s1-t13-k1-k3-k2-k4-k1)	ERROR	Incorrect asset name in block 'get_email_1'	
[20241029 13:48:43.932](https://github.com/phantomcyber/playbooks/pull/196#s1-t13-k1-k3-k3-k4-k1)	ERROR	Incorrect asset name in block 'detonate_file_1'	
[20241029 13:48:43.934](https://github.com/phantomcyber/playbooks/pull/196#s1-t13-k1-k3-k4-k4-k1)	ERROR	Incorrect asset name in block 'get_summary_report_1'

**Review by kelby-shelton — CHANGES_REQUESTED** [review]
Fix these issues:

- Playbook description empty
- Playbook notes empty
- 5 blocks missing custom names, e.g. get_summary_report_1 should be "get summary report" as a custom name
- 5 blocks missing notes tooltip
-

**Comment by MislavReversingLabs** [comment]
We'll fix those errors quickly and cummit the changes.

**Comment by MislavReversingLabs** [comment]
@kelby-shelton I corrected the files. Please have a look.

**Review by kelby-shelton — APPROVED** [review]
Looks good!

**Pull request merged**
